foggyline_user_user:
    resource: "@FoggylineUserBundle/Controller/UserController.php"
    type:     annotation

foggyline_user:
    resource: "@FoggylineUserBundle/Resources/config/routing.xml"
    prefix:   /user/
    
foggyline_sales:
    resource: "@FoggylineSalesBundle/Resources/config/routing.xml"
    prefix:   /sales/

foggyline_shipment:
    resource: "@FoggylineShipmentBundle/Resources/config/routing.xml"
    prefix:   /shipment/

foggyline_payment_card:
    resource: "@FoggylinePaymentBundle/Controller/CardController.php"
    type:     annotation

foggyline_payment:
    resource: "@FoggylinePaymentBundle/Resources/config/routing.xml"
    prefix:   /payment/

foggyline_customer_customer:
    resource: "@FoggylineCustomerBundle/Controller/CustomerController.php"
    type:     annotation

foggyline_customer:
    resource: "@FoggylineCustomerBundle/Resources/config/routing.xml"
    prefix:   /customer/

foggyline_catalog_product:
    resource: "@FoggylineCatalogBundle/Controller/ProductController.php"
    type:     annotation

foggyline_catalog_category:
    resource: "@FoggylineCatalogBundle/Controller/CategoryController.php"
    type:     annotation

foggyline_catalog:
    resource: "@FoggylineCatalogBundle/Resources/config/routing.xml"
    prefix:   /catalog/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
